### PR TITLE
Mac OS documentation

### PR DESCRIPTION
**Pull request by gotcha**
Using system python does not work anymore due to bootstrap using TLS v1 on pypi.

The code above is my best attempt. I am happy to be told wrong

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
The system Python works for me:

```
$ /usr/bin/python bootstrap.py 
Creating directory '/Users/maurits/community/buildout.python/bin'.
Creating directory '/Users/maurits/community/buildout.python/parts'.
Creating directory '/Users/maurits/community/buildout.python/eggs'.
Creating directory '/Users/maurits/community/buildout.python/develop-eggs'.
Generated script '/Users/maurits/community/buildout.python/bin/buildout'.
$ /usr/bin/python
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

This is on Mojave 10.14.6. I may very well have installed extra ssl stuff with brew.

Are you on Mojave or the new Mac OS Catalina?

**Comment by mauritsvanrees** [comment]
Your new instructions are fine too though. Maybe add them as alternative option?

**Comment by gotcha** [comment]
@mauritsvanrees I am still under Sierra 😕 I guess that might be the reason it fails for me. One more sign that I should upgrade !

Would it be useful to change the PR as an option for people lagging behind like me ?

Or just confusing because you should be on latest Mac OS ?

**Comment by mauritsvanrees** [comment]
For me, `buildout.python` exists for situations where your OS platform gives you a too new or too old Python. So you should not have to be on the latest OS either.

Several commands can fail for dozens of reasons, including a too old OS and a too new OS. So fine for me to rewrite this to an extra option in case other options fail.

Since a few months I have a new laptop, and I decided to try without `buildout.python`. I use [pyenv](https://github.com/pyenv/pyenv). And I guess a Python from `brew` as well.

**Comment by mauritsvanrees** [comment]
BTW, on Travis I see failures like this:

    Error: Couldn't find a distribution for 'buildout.extensionscripts'.

We may need to add `index = https://pypi.org/simple` to `buildout.cfg`.

**Comment by mjpieters** [comment]
The bootstrap script should take care of the dependencies, instead.

**Pull request closed without merging**
