### PR TITLE
Backport python2.7 patch to compile python2.4 on Sierra

### PR DESCRIPTION
**Pull request by mpeeters**
This refs #58

### CODE REVIEW

**Comment by aclark4life** [comment]
@mpeeters Nice, thank you! Works for me:

```
~/Developer/buildout/buildout.python mpeeters-master parts/opt/bin/python2.4 
Python 2.4.6 (#1, Apr 29 2017, 08:22:18) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit
'Use Ctrl-D (i.e. EOF) to exit.'
>>> 
```

Can you apply to 2.5 as well while we are at it?

```

2 warnings generated.
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/sysmodule.o Python/sysmodule.c
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/traceback.o Python/traceback.c
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/getopt.o Python/getopt.c
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/pystrtod.o Python/pystrtod.c
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/dynload_shlib.o Python/dynload_shlib.c
gcc -c -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Python/mactoolboxglue.o Python/mactoolboxglue.c
In file included from Python/mactoolboxglue.c:27:
Include/pymactoolbox.h:11:10: fatal error: 'QuickTime/QuickTime.h' file not found
#include <QuickTime/QuickTime.h>
         ^
1 error generated.
make: *** [Python/mactoolboxglue.o] Error 1
python-2.5-build: cmmi failed: /var/folders/_0/rjb4drfs3p97t_n1k0x5wlhw0000gn/T/tmpQtSTA4buildout-python-2.5-build
While:
  Installing python-2.5-build.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/alexclark/Developer/buildout/buildout.python/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1683, in main
    getattr(buildout, command)(args)
  File "/Users/alexclark/Developer/buildout/buildout.python/lib/python2.7/site-packages/zc/buildout/buildout.py", line 555, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/alexclark/Developer/buildout/buildout.python/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1227, in _call
    return f()
  File "build/bdist.macosx-10.12-x86_64/egg/zc/recipe/cmmi/__init__.py", line 113, in install
    self.build()
  File "/Users/alexclark/Developer/buildout/buildout.python/eggs/collective.recipe.cmmi-0.5-py2.7.egg/collective/recipe/cmmi/__init__.py", line 24, in build
    result = Base.build(self)
  File "build/bdist.macosx-10.12-x86_64/egg/zc/recipe/cmmi/__init__.py", line 196, in build
    self.cmmi(dest)
  File "/Users/alexclark/Developer/buildout/buildout.python/eggs/collective.recipe.cmmi-0.5-py2.7.egg/collective/recipe/cmmi/__init__.py", line 61, in cmmi
    system("%s %s" % (make, make_options))
  File "build/bdist.macosx-10.12-x86_64/egg/zc/recipe/cmmi/__init__.py", line 34, in system
    raise SystemError("Failed", c)
SystemError: ('Failed', 'make ')
```

**Comment by mpeeters** [comment]
@aclark4life I am currently working on the backport for python2.5 I still have an error that I will fix in the next few days

**Comment by mpeeters** [comment]
@aclark4life I finally took the time to backport the patch for python 2.5

**Comment by aclark4life** [comment]
@mpeeters Much appreciated! Works for me here (too much output to paste)

**Comment by mauritsvanrees** [comment]
I have merged it. Thank you!

**Pull request merged**
